/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.mwengine.core;

public class SWIGTYPE_p_ResizableAudioBuffer {
  private transient long swigCPtr;

  protected SWIGTYPE_p_ResizableAudioBuffer(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_ResizableAudioBuffer() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_ResizableAudioBuffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

